---
title: "Information"
---

## 📅 Dates

The training school will take place from **Monday 12th to Friday 16 October 2026**.

## 🌍 Location

The session will be held in person at the main offices of the [Archaeology Data Service](https://archaeologydataservice.ac.uk/). Please see the map below for the exact location.

The address of the ADS offices are:

> Guildhall, The Courtyard, Coney St, York YO1 9QN

```{r ads map}
#| echo: false
library(leaflet)
kings <- c(-1.0854442, 53.9597657)
popup <- paste0("<a href=https://maps.app.goo.gl/RAUtkcQVUUmy4bd96 target=_external>Google Maps</a>")
leaflet() %>% 
  addTiles() %>% 
  setView(lng = kings[1], lat = kings[2], zoom = 20) %>% 
  addMarkers(lng = kings[1], lat = kings[2], popup = popup)
```

## 📖 Expenses

The ADS Training School is facilitated through the ATRIUM project [Transnational Access Scheme](https://atrium-research.eu/travel-grants/). By applying to this scheme expenses incurred through attending the training school will be reimbursed to successful applicants.

This scheme covers the following expenses:

-   International travel (including all travel costs within the UK)
-   Accommodation for the duration of the training school
-   Subsistence expenses

## ✈️ Travelling to York

York is well connected by rail from a number of UK airports, making it easy to reach from overseas.

-   Manchester Airport – the nearest airport to the University, with a direct train to York (approx. 1h 50m)
-   Newcastle Airport – take the Tyne and Wear Metro directly from the airport to Newcastle Central Station, then a direct train to York (approx. 1 hour)
-   London airports (Heathrow, Gatwick, Stansted) – all well connected to York by train, usually via London King's Cross or Euston (approx. 2 hours from London). King's Cross is a short walk from St Pancras International, which is served by the Eurostar

You can search train times and book tickets via [National Rail](https://www.nationalrail.co.uk/).

For more information about travelling to York internationally please visit the ['Arriving from Overseas'](https://www.york.ac.uk/students/new/international/travelling-to-york/) webpage on the University of York website. More information is also accessible via the [Univeristy of York's travel webpages](https://www.york.ac.uk/about/transport-maps-parking/){.external}.

## 🏨 Accommodation

York has a number of choices for accommodation in and around the city. Please look at the [Visit York website](https://visityork.org/business-directory/category/stay) for more information. If you are accepted to the Training School, we would be happy to provide you with some suggestions about where to stay in York.
