---
title: "Training School Programme"
---

The training school will take place over five days, beginning with theoretical information, structured teaching and hands on activities and allowing time towards the end of the week to apply practices to your own datasets.

## Outline

The training school will begin by instructing participants in the foundational concepts of Linked Open Data (LOD) and semantic mapping for cultural heritage, covering key principles, benefits, and relevant standards and controlled vocabularies. Participants will learn about the development and structure of the ARIADNE portal and the data standard that underpins it - the AO-Cat ontology, a subset of CIDOC-CRM framework.

The remainder of the training school will be dedicated to developing practical skills for data mapping, by using ARIADNE’s mapping tools and resources including the X3ML Toolkit and Vocabulary mapping tool, as well as related software such as Open Refine. By the end of the training week, participants will have gained all the skills they need to map their archaeological and heritage data to the ARIADNE portal.

No previous experience is necessary, however, participants will be required to have a real-world dataset that they would like to map to the ARIADNE Portal. The workshop will use example datasets to train participants, which will lead them to map their own data to the ARIADNE portal with support from staff from the ADS and other experts.

This page provides the preliminary programme for the training school, including the topics covered. Further details will be added below as topics and events are finalised.

------------------------------------------------------------------------

## Learning Objectives

1.  Explain the key principles of Linked Open Data and the relevance for archaeological and heritage data.
2.  Describe the structure of the ARIADNE portal and the AO-Cat ontology.
3.  Apply data preparation techniques using OpenRefine to clean and structure a real-world dataset for mapping.
4.  Apply the use of the X3ML Toolkit and Vocabulary Mapping Tool to map dataset fields to AO-Cat/CIDOC-CRM classes and properties.
5.  Begin to produce a complete semantic mapping of their own dataset, ready for aggregation to the ARIADNE portal

## 🗓️ Schedule

Training begins each day at 9.30am and finishes at 4pm. Coffee breaks will take place in the ADS Offices. Lunch is not provided but there are a number of cafes and restaurants are in close proximity.

+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Day                        | Activity                                                                                                                                                                                                                                                        |
+:===========================+:================================================================================================================================================================================================================================================================+
| **Monday 12th October**    | 10:00 - Welcome to the ADS -Julian Richards and Tim Evans, ADS 10:30 - Participant Introductions (5 mins each)                                                                                                                                                  |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 13:00-14:00 Lunch Break 14:00 - An Introduction to Linked Open Data (principles, URIs, RDF/triples, benefits & limitations) - Nicky Garland                                                                                                                     |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 16:30 - Session ends                                                                                                                                                                                                                                            |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Tuesday 13th October**   | 09:30 - An Introduction to the ARIADNE Portal, AO-Cat and the CIDOC CRM ecosystem - Maria Theodoridou & Émilie Pagé-Perron                                                                                                                                      |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 13:00-14:00 Lunch Break                                                                                                                                                                                                                                         |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 14:00 - Data Preparation with Open Refine - Sarah Middle (with assistance from all)                                                                                                                                                                             |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 16:30 - Session ends                                                                                                                                                                                                                                            |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Wednesday 14th October** | 9:30 - CIDOC-CRM Mapping Strategies and Tools (3M) - Maria Theodoridou                                                                                                                                                                                          |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 13:00-14:00 Lunch Break                                                                                                                                                                                                                                         |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 14:00 - Hands on Session - Using the 3M tool - Maria Theodoridou (with assistance from all)                                                                                                                                                                     |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 16:30 - Session ends                                                                                                                                                                                                                                            |
|                            |                                                                                                                                                                                                                                                                 |
|                            | ------------------------------------------------------------------------                                                                                                                                                                                        |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 16.30-17.30 Plenary Lecture (optional) - Dr Emilie Page-Perron, ADS - [Towards Universal Access to Cuneiform Heritage (TUA-CH)](https://archaeologydataservice.ac.uk/about/projects/towards-universal-access-to-cuneiform-heritage-tua-ch-research-programme/)  |
|                            |                                                                                                                                                                                                                                                                 |
|                            | Followed by drinks in the local pub.                                                                                                                                                                                                                            |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Thursday 15th October**  | 09:30 - Controlled Vocabularies and Vocabulary Matching Tools Maria Theodoridou and Sarah Middle                                                                                                                                                                |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 13:00-14:00 Lunch Break                                                                                                                                                                                                                                         |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 14:00 - Hands on Session - Using the Vocabulary matching tool (AAT) - Sarah Middle (with assistance from all)                                                                                                                                                   |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 16.00 - Peer Check in - in pairs review each other's mapping-so-far (i.e. does it use correct AO-Cat classes? is vocabulary aligned?) - Nicky Garland                                                                                                           |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 16:30 - Session ends                                                                                                                                                                                                                                            |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Friday 16th October**    | 09:30 - Hands on Session - Mapping to ARIADNE with our own datasets - All                                                                                                                                                                                       |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 13:00-14:00 Lunch Break                                                                                                                                                                                                                                         |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 14:00 - Training School Wrap up - ARIADNE Membership/Q&A Session / Evaluation - Nicky Garland                                                                                                                                                                   |
|                            |                                                                                                                                                                                                                                                                 |
|                            | 15:00 - Training School ends                                                                                                                                                                                                                                    |
+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
